apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-demo-topic
          patternType: literal
        operation: 
        - Write
        host: '*'
        type: allow
        host: '*'
        type: allow
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-consumer
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - resource:
          type: topic
          name: kafka-demo-topic
          patternType: literal
        operation: Read
        host: '*'
        type: allow
      - resource:
          type: group
          name: kafka-demo-group
          patternType: literal
        operation: 
        - Read
        host: '*'
        type: allow
    type: simple
