apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-with-kraft-controller
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi  ###100Gi
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-with-kraft-broker
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi  ###100Gi
---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-with-kraft
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: sasl
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: mtls
        port: 9094
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
