apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: sasl-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  authentication:
    type: scram-sha-512
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: mtls-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-with-kraft
spec:
  authentication:
    type: tls
